"""initial_schema

Revision ID: 8de48d5c297e
Revises: 
Create Date: 2026-04-07 14:08:57.995866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de48d5c297e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_listing',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_listing_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('images_json', sa.Text(), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=True),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('listing_format', sa.String(length=32), nullable=False),
    sa.Column('current_price_jpy', sa.Integer(), nullable=False),
    sa.Column('price_buy_now_jpy', sa.Integer(), nullable=True),
    sa.Column('domestic_shipping_jpy', sa.Integer(), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_prefecture', sa.String(length=128), nullable=True),
    sa.Column('condition_text', sa.String(length=256), nullable=True),
    sa.Column('lot_size_hint', sa.Integer(), nullable=False),
    sa.Column('raw_attributes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('listing_id'),
    sa.UniqueConstraint('source', 'source_listing_id', name='uq_raw_listing_source_id')
    )
    op.create_index(op.f('ix_raw_listing_source'), 'raw_listing', ['source'], unique=False)
    op.create_index(op.f('ix_raw_listing_source_listing_id'), 'raw_listing', ['source_listing_id'], unique=False)
    op.create_table('report_run',
    sa.Column('report_run_id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_path', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('report_run_id')
    )
    op.create_index(op.f('ix_report_run_report_date'), 'report_run', ['report_date'], unique=True)
    op.create_table('auction_prediction',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('auction_low_win_price_jpy', sa.Integer(), nullable=False),
    sa.Column('auction_expected_final_price_jpy', sa.Integer(), nullable=False),
    sa.Column('auction_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('classification_result',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('classification_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('line', sa.String(length=128), nullable=True),
    sa.Column('nib_material', sa.String(length=32), nullable=True),
    sa.Column('nib_size', sa.String(length=32), nullable=True),
    sa.Column('condition_grade', sa.String(length=32), nullable=False),
    sa.Column('condition_flags_json', sa.Text(), nullable=False),
    sa.Column('item_count_estimate', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('condition_confidence', sa.Float(), nullable=False),
    sa.Column('lot_decomposition_confidence', sa.Float(), nullable=False),
    sa.Column('text_evidence', sa.Text(), nullable=True),
    sa.Column('image_evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_classification_result_classification_id'), 'classification_result', ['classification_id'], unique=False)
    op.create_table('deal_score',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('expected_profit_jpy', sa.Integer(), nullable=False),
    sa.Column('expected_profit_pct', sa.Float(), nullable=False),
    sa.Column('risk_adjusted_profit_jpy', sa.Integer(), nullable=False),
    sa.Column('confidence_overall', sa.Float(), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('risk_flags_json', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_deal_score_bucket'), 'deal_score', ['bucket'], unique=False)
    op.create_table('proxy_option_estimate',
    sa.Column('estimate_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('proxy_name', sa.String(length=64), nullable=False),
    sa.Column('total_cost_jpy', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.String(length=128), nullable=True),
    sa.Column('coupon_discount_jpy', sa.Integer(), nullable=False),
    sa.Column('cost_confidence', sa.Float(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('estimate_id'),
    sa.UniqueConstraint('listing_id', 'proxy_name', name='uq_proxy_option_per_listing')
    )
    op.create_index(op.f('ix_proxy_option_estimate_listing_id'), 'proxy_option_estimate', ['listing_id'], unique=False)
    op.create_index(op.f('ix_proxy_option_estimate_proxy_name'), 'proxy_option_estimate', ['proxy_name'], unique=False)
    op.create_table('report_item',
    sa.Column('report_item_id', sa.String(length=36), nullable=False),
    sa.Column('report_run_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_run_id'], ['report_run.report_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_item_id'),
    sa.UniqueConstraint('report_run_id', 'listing_id', name='uq_report_listing')
    )
    op.create_index(op.f('ix_report_item_bucket'), 'report_item', ['bucket'], unique=False)
    op.create_index(op.f('ix_report_item_listing_id'), 'report_item', ['listing_id'], unique=False)
    op.create_index(op.f('ix_report_item_report_run_id'), 'report_item', ['report_run_id'], unique=False)
    op.create_table('valuation_prediction',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('resale_pred_jpy', sa.Integer(), nullable=False),
    sa.Column('resale_ci_low_jpy', sa.Integer(), nullable=False),
    sa.Column('resale_ci_high_jpy', sa.Integer(), nullable=False),
    sa.Column('valuation_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listing.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_prediction')
    op.drop_index(op.f('ix_report_item_report_run_id'), table_name='report_item')
    op.drop_index(op.f('ix_report_item_listing_id'), table_name='report_item')
    op.drop_index(op.f('ix_report_item_bucket'), table_name='report_item')
    op.drop_table('report_item')
    op.drop_index(op.f('ix_proxy_option_estimate_proxy_name'), table_name='proxy_option_estimate')
    op.drop_index(op.f('ix_proxy_option_estimate_listing_id'), table_name='proxy_option_estimate')
    op.drop_table('proxy_option_estimate')
    op.drop_index(op.f('ix_deal_score_bucket'), table_name='deal_score')
    op.drop_table('deal_score')
    op.drop_index(op.f('ix_classification_result_classification_id'), table_name='classification_result')
    op.drop_table('classification_result')
    op.drop_table('auction_prediction')
    op.drop_index(op.f('ix_report_run_report_date'), table_name='report_run')
    op.drop_table('report_run')
    op.drop_index(op.f('ix_raw_listing_source_listing_id'), table_name='raw_listing')
    op.drop_index(op.f('ix_raw_listing_source'), table_name='raw_listing')
    op.drop_table('raw_listing')
    # ### end Alembic commands ###
